# coding: utf-8

"""
    BEAI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.57.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from beai.models.create_interview_request_candidate import CreateInterviewRequestCandidate
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CreateInterviewRequest(BaseModel):
    """
    `POST /v1/interviews` request validation (public-api step 5, SPEC.md §3.3 \"Create interview — request\", `CreateInterviewRequest` schema).  FORMAT only — `project_id`'s prefix/existence/tenancy, the project-active gate, the `exit_redirect_url` allowed-domain check and the duplicate- enrolment check all need the resolved `Project`/`Organization` and live in `App\\Http\\Controllers\\PublicApi\\InterviewController::store()` and `App\\Actions\\PublicApi\\EnrolCandidate` — mirroring `App\\Http\\Controllers\\PublicApi\\ProjectController::show()`'s own \"decode,  * never bind\" discipline for a public-id path/body field (G-36).  `authorize()` returns `true` unconditionally: scope enforcement is `App\\Http\\Middleware\\PublicApi\\RequireScope`'s job, applied per-route in `routes/api.php` (`scope:interviews:write`) — the SAME division of labour every other `/v1` write endpoint follows.
    """ # noqa: E501
    candidate: CreateInterviewRequestCandidate
    exit_redirect_url: Optional[Annotated[str, Field(strict=True, max_length=2048)]] = Field(default=None, description="https-only (SPEC.md §3.3 \"It must be https\") — `url` alone accepts http too, so the scheme is checked separately. max:2048 (gga round 3 finding 2) — matches the migration's own `varchar(2048)` column width for this field, and the admin `StoreProjectRequest`/`UpdateProjectRequest` validation rule for the same-shaped `exit_redirect_url` field.")
    metadata: Optional[Dict[str, StrictStr]] = Field(default=None, description="Free-form key/value pairs (≤ 20 keys, key ≤ 40 chars, value ≤ 500 chars).")
    project_id: StrictStr
    __properties: ClassVar[List[str]] = ["candidate", "exit_redirect_url", "metadata", "project_id"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreateInterviewRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of candidate
        if self.candidate:
            _dict['candidate'] = self.candidate.to_dict()
        # set to None if exit_redirect_url (nullable) is None
        # and model_fields_set contains the field
        if self.exit_redirect_url is None and "exit_redirect_url" in self.model_fields_set:
            _dict['exit_redirect_url'] = None

        # set to None if metadata (nullable) is None
        # and model_fields_set contains the field
        if self.metadata is None and "metadata" in self.model_fields_set:
            _dict['metadata'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreateInterviewRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "candidate": CreateInterviewRequestCandidate.from_dict(obj["candidate"]) if obj.get("candidate") is not None else None,
            "exit_redirect_url": obj.get("exit_redirect_url"),
            "metadata": obj.get("metadata"),
            "project_id": obj.get("project_id")
        })
        return _obj


