/* tslint:disable */
/* eslint-disable */
/**
 * BEAI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.57.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateInterviewRequestCandidate } from './CreateInterviewRequestCandidate';
import {
    CreateInterviewRequestCandidateFromJSON,
    CreateInterviewRequestCandidateFromJSONTyped,
    CreateInterviewRequestCandidateToJSON,
    CreateInterviewRequestCandidateToJSONTyped,
} from './CreateInterviewRequestCandidate';

/**
 * `POST /v1/interviews` request validation (public-api step 5, SPEC.md §3.3
 * "Create interview — request", `CreateInterviewRequest` schema).
 * 
 * FORMAT only — `project_id`'s prefix/existence/tenancy, the project-active
 * gate, the `exit_redirect_url` allowed-domain check and the duplicate-
 * enrolment check all need the resolved `Project`/`Organization` and live
 * in `App\Http\Controllers\PublicApi\InterviewController::store()` and
 * `App\Actions\PublicApi\EnrolCandidate` — mirroring
 * `App\Http\Controllers\PublicApi\ProjectController::show()`'s own "decode,
 *  * never bind" discipline for a public-id path/body field (G-36).
 * 
 * `authorize()` returns `true` unconditionally: scope enforcement is
 * `App\Http\Middleware\PublicApi\RequireScope`'s job, applied per-route in
 * `routes/api.php` (`scope:interviews:write`) — the SAME division of labour
 * every other `/v1` write endpoint follows.
 * @export
 * @interface CreateInterviewRequest
 */
export interface CreateInterviewRequest {
    /**
     * 
     */
    candidate: CreateInterviewRequestCandidate;
    /**
     * https-only (SPEC.md §3.3 "It must be https") — `url` alone
     * accepts http too, so the scheme is checked separately.
     * max:2048 (gga round 3 finding 2) — matches the migration's own
     * `varchar(2048)` column width for this field, and the admin
     * `StoreProjectRequest`/`UpdateProjectRequest` validation rule
     * for the same-shaped `exit_redirect_url` field.
     */
    exitRedirectUrl?: string | null;
    /**
     * Free-form key/value pairs (≤ 20 keys, key ≤ 40 chars, value ≤ 500 chars).
     */
    metadata?: { [key: string]: string; } | null;
    /**
     * 
     */
    projectId: string;
}

/**
 * Check if a given object implements the CreateInterviewRequest interface.
 */
export function instanceOfCreateInterviewRequest(value: object): value is CreateInterviewRequest {
    if (!('candidate' in value) || value['candidate'] === undefined) return false;
    if ((!('projectId' in (value as Record<string, any>)) && !('project_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['projectId'] === undefined && (value as Record<string, any>)['project_id'] === undefined)) return false;
    return true;
}

export function CreateInterviewRequestFromJSON(json: any): CreateInterviewRequest {
    return CreateInterviewRequestFromJSONTyped(json, false);
}

export function CreateInterviewRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateInterviewRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'candidate': CreateInterviewRequestCandidateFromJSON(json['candidate']),
        'exitRedirectUrl': json['exit_redirect_url'] === undefined ? undefined : json['exit_redirect_url'] === null ? null : json['exit_redirect_url'],
        'metadata': json['metadata'] === undefined ? undefined : json['metadata'] === null ? null : json['metadata'],
        'projectId': json['project_id'],
    };
}

export function CreateInterviewRequestToJSON(json: any): CreateInterviewRequest {
    return CreateInterviewRequestToJSONTyped(json, false);
}

export function CreateInterviewRequestToJSONTyped(value?: CreateInterviewRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'candidate': CreateInterviewRequestCandidateToJSON(value['candidate']),
        'exit_redirect_url': value['exitRedirectUrl'],
        'metadata': value['metadata'],
        'project_id': value['projectId'],
    };
}

