/* tslint:disable */
/* eslint-disable */
/**
 * BEAI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.57.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateInterviewRequestCandidate
 */
export interface CreateInterviewRequestCandidate {
    /**
     * 
     */
    candidateRef: string;
    /**
     * 
     */
    displayName: string;
    /**
     * max:255 (gga round 3 finding 2) — matches participants.email's
     * own column width; without it a caller-supplied value long
     * enough to overflow that column reaches the database as a
     * truncation error (500) instead of the intended 422 here.
     */
    email: string;
    /**
     * ISO 639-1, matching `openapi.yaml`'s `Language` schema pattern
     * exactly (`^[a-z]{2}$`) — no further allow-list check: the
     * contract does not restrict `candidate.language` to a
     * per-project or per-platform locale set, and this endpoint has
     * no such catalogue to validate against (unlike
     * `config/translatable.php`'s `supported_locales`, which is a
     * BACKOFFICE UI concept).
     */
    language?: string | null;
}

/**
 * Check if a given object implements the CreateInterviewRequestCandidate interface.
 */
export function instanceOfCreateInterviewRequestCandidate(value: object): value is CreateInterviewRequestCandidate {
    if ((!('candidateRef' in (value as Record<string, any>)) && !('candidate_ref' in (value as Record<string, any>))) || ((value as Record<string, any>)['candidateRef'] === undefined && (value as Record<string, any>)['candidate_ref'] === undefined)) return false;
    if ((!('displayName' in (value as Record<string, any>)) && !('display_name' in (value as Record<string, any>))) || ((value as Record<string, any>)['displayName'] === undefined && (value as Record<string, any>)['display_name'] === undefined)) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function CreateInterviewRequestCandidateFromJSON(json: any): CreateInterviewRequestCandidate {
    return CreateInterviewRequestCandidateFromJSONTyped(json, false);
}

export function CreateInterviewRequestCandidateFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateInterviewRequestCandidate {
    if (json == null) {
        return json;
    }
    return {
        
        'candidateRef': json['candidate_ref'],
        'displayName': json['display_name'],
        'email': json['email'],
        'language': json['language'] === undefined ? undefined : json['language'] === null ? null : json['language'],
    };
}

export function CreateInterviewRequestCandidateToJSON(json: any): CreateInterviewRequestCandidate {
    return CreateInterviewRequestCandidateToJSONTyped(json, false);
}

export function CreateInterviewRequestCandidateToJSONTyped(value?: CreateInterviewRequestCandidate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'candidate_ref': value['candidateRef'],
        'display_name': value['displayName'],
        'email': value['email'],
        'language': value['language'],
    };
}

