/* tslint:disable */
/* eslint-disable */
/**
 * BEAI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.57.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PublicInterviewProject } from './PublicInterviewProject';
import {
    PublicInterviewProjectFromJSON,
    PublicInterviewProjectFromJSONTyped,
    PublicInterviewProjectToJSON,
    PublicInterviewProjectToJSONTyped,
} from './PublicInterviewProject';
import type { PublicInterviewProgress } from './PublicInterviewProgress';
import {
    PublicInterviewProgressFromJSON,
    PublicInterviewProgressFromJSONTyped,
    PublicInterviewProgressToJSON,
    PublicInterviewProgressToJSONTyped,
} from './PublicInterviewProgress';

/**
 * 
 * @export
 * @interface PublicInterview
 */
export interface PublicInterview {
    /**
     * 
     */
    candidateRef: string;
    /**
     * 
     */
    completedAt: string | null;
    /**
     * 
     */
    createdAt: string;
    /**
     * 
     */
    displayName: string;
    /**
     * 
     */
    email: string;
    /**
     * 
     */
    exitRedirectUrl: string | null;
    /**
     * ALWAYS null here — a plain read never has a fresh session
     * token to embed one for. Exported as `string|null` (not the
     * literal `null` this line alone would infer) by
     * `App\Support\Scramble\InterviewHostedUrlNullableExtension` —
     * see that class's own docblock; step 6 review follow-up, Part
     * A item 4 removed the runtime config hack this used to
     * route through.
     */
    hostedUrl: string | null;
    /**
     * 
     */
    id: string;
    /**
     * 
     */
    language: string;
    /**
     * 
     */
    livemode: boolean;
    /**
     * 
     */
    metadata: Array<any>;
    /**
     * 
     */
    progress: PublicInterviewProgress;
    /**
     * 
     */
    project: PublicInterviewProject;
    /**
     * 
     */
    projectId: string;
    /**
     * G-01: true iff an `interview_recordings` row exists for this
     * participant (audio only — video is never exposed, see
     * `App\Http\Controllers\PublicApi\RecordingController`'s own
     * docblock). gga review, step 6 follow-up, finding 5: this used
     * to be a hardcoded `false` left over from before step 6 built
     * the recording pipeline.
     * (bool) cast — `self::recordingReady()`'s return flows through
     * a loop-populated array (`recordingReadyForMany()`'s own
     * `$result[...] = true;`), which Scramble's export could not
     * narrow precisely and rendered as `anyOf: [string, boolean]`
     * without this cast, despite the method's own native `: bool`
     * return type. Caught via the `scramble:export` diff, not a
     * test — same class of fix as
     * `App\Support\Scramble\InterviewHostedUrlNullableExtension`.
     */
    recordingReady: boolean;
    /**
     * 
     */
    roleCode: string | null;
    /**
     * 
     */
    scoringReady: boolean;
    /**
     * 
     */
    startedAt: string | null;
    /**
     * 
     */
    status: string;
    /**
     * 
     */
    transcriptReady: boolean;
    /**
     * 
     */
    updatedAt: string;
}

/**
 * Check if a given object implements the PublicInterview interface.
 */
export function instanceOfPublicInterview(value: object): value is PublicInterview {
    if ((!('candidateRef' in (value as Record<string, any>)) && !('candidate_ref' in (value as Record<string, any>))) || ((value as Record<string, any>)['candidateRef'] === undefined && (value as Record<string, any>)['candidate_ref'] === undefined)) return false;
    if ((!('completedAt' in (value as Record<string, any>)) && !('completed_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['completedAt'] === undefined && (value as Record<string, any>)['completed_at'] === undefined)) return false;
    if ((!('createdAt' in (value as Record<string, any>)) && !('created_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['createdAt'] === undefined && (value as Record<string, any>)['created_at'] === undefined)) return false;
    if ((!('displayName' in (value as Record<string, any>)) && !('display_name' in (value as Record<string, any>))) || ((value as Record<string, any>)['displayName'] === undefined && (value as Record<string, any>)['display_name'] === undefined)) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if ((!('exitRedirectUrl' in (value as Record<string, any>)) && !('exit_redirect_url' in (value as Record<string, any>))) || ((value as Record<string, any>)['exitRedirectUrl'] === undefined && (value as Record<string, any>)['exit_redirect_url'] === undefined)) return false;
    if ((!('hostedUrl' in (value as Record<string, any>)) && !('hosted_url' in (value as Record<string, any>))) || ((value as Record<string, any>)['hostedUrl'] === undefined && (value as Record<string, any>)['hosted_url'] === undefined)) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('language' in value) || value['language'] === undefined) return false;
    if (!('livemode' in value) || value['livemode'] === undefined) return false;
    if (!('metadata' in value) || value['metadata'] === undefined) return false;
    if (!('progress' in value) || value['progress'] === undefined) return false;
    if (!('project' in value) || value['project'] === undefined) return false;
    if ((!('projectId' in (value as Record<string, any>)) && !('project_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['projectId'] === undefined && (value as Record<string, any>)['project_id'] === undefined)) return false;
    if ((!('recordingReady' in (value as Record<string, any>)) && !('recording_ready' in (value as Record<string, any>))) || ((value as Record<string, any>)['recordingReady'] === undefined && (value as Record<string, any>)['recording_ready'] === undefined)) return false;
    if ((!('roleCode' in (value as Record<string, any>)) && !('role_code' in (value as Record<string, any>))) || ((value as Record<string, any>)['roleCode'] === undefined && (value as Record<string, any>)['role_code'] === undefined)) return false;
    if ((!('scoringReady' in (value as Record<string, any>)) && !('scoring_ready' in (value as Record<string, any>))) || ((value as Record<string, any>)['scoringReady'] === undefined && (value as Record<string, any>)['scoring_ready'] === undefined)) return false;
    if ((!('startedAt' in (value as Record<string, any>)) && !('started_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['startedAt'] === undefined && (value as Record<string, any>)['started_at'] === undefined)) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if ((!('transcriptReady' in (value as Record<string, any>)) && !('transcript_ready' in (value as Record<string, any>))) || ((value as Record<string, any>)['transcriptReady'] === undefined && (value as Record<string, any>)['transcript_ready'] === undefined)) return false;
    if ((!('updatedAt' in (value as Record<string, any>)) && !('updated_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['updatedAt'] === undefined && (value as Record<string, any>)['updated_at'] === undefined)) return false;
    return true;
}

export function PublicInterviewFromJSON(json: any): PublicInterview {
    return PublicInterviewFromJSONTyped(json, false);
}

export function PublicInterviewFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicInterview {
    if (json == null) {
        return json;
    }
    return {
        
        'candidateRef': json['candidate_ref'],
        'completedAt': json['completed_at'],
        'createdAt': json['created_at'],
        'displayName': json['display_name'],
        'email': json['email'],
        'exitRedirectUrl': json['exit_redirect_url'],
        'hostedUrl': json['hosted_url'],
        'id': json['id'],
        'language': json['language'],
        'livemode': json['livemode'],
        'metadata': json['metadata'],
        'progress': PublicInterviewProgressFromJSON(json['progress']),
        'project': PublicInterviewProjectFromJSON(json['project']),
        'projectId': json['project_id'],
        'recordingReady': json['recording_ready'],
        'roleCode': json['role_code'],
        'scoringReady': json['scoring_ready'],
        'startedAt': json['started_at'],
        'status': json['status'],
        'transcriptReady': json['transcript_ready'],
        'updatedAt': json['updated_at'],
    };
}

export function PublicInterviewToJSON(json: any): PublicInterview {
    return PublicInterviewToJSONTyped(json, false);
}

export function PublicInterviewToJSONTyped(value?: PublicInterview | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'candidate_ref': value['candidateRef'],
        'completed_at': value['completedAt'],
        'created_at': value['createdAt'],
        'display_name': value['displayName'],
        'email': value['email'],
        'exit_redirect_url': value['exitRedirectUrl'],
        'hosted_url': value['hostedUrl'],
        'id': value['id'],
        'language': value['language'],
        'livemode': value['livemode'],
        'metadata': value['metadata'],
        'progress': PublicInterviewProgressToJSON(value['progress']),
        'project': PublicInterviewProjectToJSON(value['project']),
        'project_id': value['projectId'],
        'recording_ready': value['recordingReady'],
        'role_code': value['roleCode'],
        'scoring_ready': value['scoringReady'],
        'started_at': value['startedAt'],
        'status': value['status'],
        'transcript_ready': value['transcriptReady'],
        'updated_at': value['updatedAt'],
    };
}

