/* tslint:disable */
/* eslint-disable */
/**
 * BEAI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.57.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type PublicApiHealth200Response,
    PublicApiHealth200ResponseFromJSON,
    PublicApiHealth200ResponseToJSON,
} from '../models/PublicApiHealth200Response';

/**
 * 
 */
export class HealthApi extends runtime.BaseAPI {

    /**
     * Creates request options for publicApiHealth without sending the request
     */
    async publicApiHealthRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/health`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Machine-readable status payloads are exempt from the i18n mandate (D31, wrapper CLAUDE.md \"Machine-facing responses are not localized\").
     * Return the literal, non-localized `{\"status\":\"ok\"}` body the contract requires
     */
    async publicApiHealthRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PublicApiHealth200Response>> {
        const requestOptions = await this.publicApiHealthRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PublicApiHealth200ResponseFromJSON(jsonValue));
    }

    /**
     * Machine-readable status payloads are exempt from the i18n mandate (D31, wrapper CLAUDE.md \"Machine-facing responses are not localized\").
     * Return the literal, non-localized `{\"status\":\"ok\"}` body the contract requires
     */
    async publicApiHealth(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PublicApiHealth200Response> {
        const response = await this.publicApiHealthRaw(initOverrides);
        return await response.value();
    }

}
