/* tslint:disable */
/* eslint-disable */
/**
 * BEAI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.57.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type CreateInterviewRequest,
    CreateInterviewRequestFromJSON,
    CreateInterviewRequestToJSON,
} from '../models/CreateInterviewRequest';
import {
    type InlineObject,
    InlineObjectFromJSON,
    InlineObjectToJSON,
} from '../models/InlineObject';
import {
    type InlineObject1,
    InlineObject1FromJSON,
    InlineObject1ToJSON,
} from '../models/InlineObject1';
import {
    type PublicApiExportsIndex400Response,
    PublicApiExportsIndex400ResponseFromJSON,
    PublicApiExportsIndex400ResponseToJSON,
} from '../models/PublicApiExportsIndex400Response';
import {
    type PublicApiInterviewsAnswers200Response,
    PublicApiInterviewsAnswers200ResponseFromJSON,
    PublicApiInterviewsAnswers200ResponseToJSON,
} from '../models/PublicApiInterviewsAnswers200Response';
import {
    type PublicApiInterviewsEvents200Response,
    PublicApiInterviewsEvents200ResponseFromJSON,
    PublicApiInterviewsEvents200ResponseToJSON,
} from '../models/PublicApiInterviewsEvents200Response';
import {
    type PublicApiInterviewsIndex200Response,
    PublicApiInterviewsIndex200ResponseFromJSON,
    PublicApiInterviewsIndex200ResponseToJSON,
} from '../models/PublicApiInterviewsIndex200Response';
import {
    type PublicApiInterviewsScoring200Response,
    PublicApiInterviewsScoring200ResponseFromJSON,
    PublicApiInterviewsScoring200ResponseToJSON,
} from '../models/PublicApiInterviewsScoring200Response';
import {
    type PublicApiInterviewsStore201Response,
    PublicApiInterviewsStore201ResponseFromJSON,
    PublicApiInterviewsStore201ResponseToJSON,
} from '../models/PublicApiInterviewsStore201Response';
import {
    type PublicApiInterviewsStore409Response,
    PublicApiInterviewsStore409ResponseFromJSON,
    PublicApiInterviewsStore409ResponseToJSON,
} from '../models/PublicApiInterviewsStore409Response';
import {
    type PublicApiInterviewsTranscript200Response,
    PublicApiInterviewsTranscript200ResponseFromJSON,
    PublicApiInterviewsTranscript200ResponseToJSON,
} from '../models/PublicApiInterviewsTranscript200Response';
import {
    type PublicInterview,
    PublicInterviewFromJSON,
    PublicInterviewToJSON,
} from '../models/PublicInterview';

export interface PublicApiInterviewsAnswersRequest {
    /**
     * 
     */
    interview: string;
}

export interface PublicApiInterviewsEventsRequest {
    /**
     * 
     */
    interview: string;
    /**
     * Opaque pagination cursor from a previous page's next_cursor. Omit for the first page. A present but malformed value answers 400 invalid_cursor.
     */
    cursor?: string;
    /**
     * Page size, 1-100 (default 25). Out of range answers 400 validation_failed.
     */
    limit?: number;
}

export interface PublicApiInterviewsIndexRequest {
    /**
     * 
     */
    status?: string;
    /**
     * 
     */
    projectId?: string;
    /**
     * 
     */
    email?: string;
    /**
     * 
     */
    candidateRef?: string;
    /**
     * 
     */
    metadata?: string;
    /**
     * Inclusive lower bound on created_at. Strict ISO 8601 date-time, UTC (Z) or a numeric offset, e.g. 2026-01-01T00:00:00Z. An invalid or non-ISO-8601 value answers 400 validation_failed.
     */
    createdAfter?: string;
    /**
     * Exclusive upper bound on created_at. Strict ISO 8601 date-time, UTC (Z) or a numeric offset, e.g. 2026-01-01T00:00:00Z. An invalid or non-ISO-8601 value answers 400 validation_failed.
     */
    createdBefore?: string;
    /**
     * Opaque pagination cursor from a previous page's next_cursor. Omit for the first page. A present but malformed value answers 400 invalid_cursor.
     */
    cursor?: string;
    /**
     * Page size, 1-100 (default 25). Out of range answers 400 validation_failed.
     */
    limit?: number;
    /**
     * Comma-separated related resources to inline. Supported: project.
     */
    expand?: string;
}

export interface PublicApiInterviewsScoringRequest {
    /**
     * 
     */
    interview: string;
}

export interface PublicApiInterviewsShowRequest {
    /**
     * 
     */
    interview: string;
    /**
     * Comma-separated related resources to inline. Supported: project.
     */
    expand?: string;
}

export interface PublicApiInterviewsStoreRequest {
    /**
     * 
     */
    createInterviewRequest: CreateInterviewRequest;
}

export interface PublicApiInterviewsTranscriptRequest {
    /**
     * 
     */
    interview: string;
}

/**
 * 
 */
export class InterviewApi extends runtime.BaseAPI {

    /**
     * Creates request options for publicApiInterviewsAnswers without sending the request
     */
    async publicApiInterviewsAnswersRequestOpts(requestParameters: PublicApiInterviewsAnswersRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['interview'] == null) {
            throw new runtime.RequiredError(
                'interview',
                'Required parameter "interview" was null or undefined when calling publicApiInterviewsAnswers().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("apiKey", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/interviews/{interview}/answers`;
        urlPath = urlPath.replace('{interview}', encodeURIComponent(String(requestParameters['interview'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * `GET /v1/interviews/{id}/answers` — SPEC.md §3.3, same read gate as the transcript
     */
    async publicApiInterviewsAnswersRaw(requestParameters: PublicApiInterviewsAnswersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PublicApiInterviewsAnswers200Response>> {
        const requestOptions = await this.publicApiInterviewsAnswersRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PublicApiInterviewsAnswers200ResponseFromJSON(jsonValue));
    }

    /**
     * `GET /v1/interviews/{id}/answers` — SPEC.md §3.3, same read gate as the transcript
     */
    async publicApiInterviewsAnswers(requestParameters: PublicApiInterviewsAnswersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PublicApiInterviewsAnswers200Response> {
        const response = await this.publicApiInterviewsAnswersRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for publicApiInterviewsEvents without sending the request
     */
    async publicApiInterviewsEventsRequestOpts(requestParameters: PublicApiInterviewsEventsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['interview'] == null) {
            throw new runtime.RequiredError(
                'interview',
                'Required parameter "interview" was null or undefined when calling publicApiInterviewsEvents().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("apiKey", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/interviews/{interview}/events`;
        urlPath = urlPath.replace('{interview}', encodeURIComponent(String(requestParameters['interview'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * `cursor`/`limit` documented explicitly (step 6 review follow-up, finding 14) — `CursorPage::paginateAscending()` reads both directly off `$request` from INSIDE `App\\Support\\PublicApi\\CursorPage`, one call frame away from this method\'s own body, which is why Scramble\'s own static-analysis auto-detection (which scans a controller method\'s own body for `$request->query()`/`$request-> integer()` calls) never picked them up — the exported spec previously documented only the `interview` path parameter for this operation.
     * `GET /v1/interviews/{id}/events` — SPEC.md §3.3, `App\\Support\\ PublicApi\\CursorPage` in its ASCENDING form (G-12: the one documented exception to `created_at desc`). `InterviewEvent.public_id` (`evt_`) is what every real row already carries — see that model\'s own docblock; no participant special-cases its absence
     */
    async publicApiInterviewsEventsRaw(requestParameters: PublicApiInterviewsEventsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PublicApiInterviewsEvents200Response>> {
        const requestOptions = await this.publicApiInterviewsEventsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PublicApiInterviewsEvents200ResponseFromJSON(jsonValue));
    }

    /**
     * `cursor`/`limit` documented explicitly (step 6 review follow-up, finding 14) — `CursorPage::paginateAscending()` reads both directly off `$request` from INSIDE `App\\Support\\PublicApi\\CursorPage`, one call frame away from this method\'s own body, which is why Scramble\'s own static-analysis auto-detection (which scans a controller method\'s own body for `$request->query()`/`$request-> integer()` calls) never picked them up — the exported spec previously documented only the `interview` path parameter for this operation.
     * `GET /v1/interviews/{id}/events` — SPEC.md §3.3, `App\\Support\\ PublicApi\\CursorPage` in its ASCENDING form (G-12: the one documented exception to `created_at desc`). `InterviewEvent.public_id` (`evt_`) is what every real row already carries — see that model\'s own docblock; no participant special-cases its absence
     */
    async publicApiInterviewsEvents(requestParameters: PublicApiInterviewsEventsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PublicApiInterviewsEvents200Response> {
        const response = await this.publicApiInterviewsEventsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for publicApiInterviewsIndex without sending the request
     */
    async publicApiInterviewsIndexRequestOpts(requestParameters: PublicApiInterviewsIndexRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['projectId'] != null) {
            queryParameters['project_id'] = requestParameters['projectId'];
        }

        if (requestParameters['email'] != null) {
            queryParameters['email'] = requestParameters['email'];
        }

        if (requestParameters['candidateRef'] != null) {
            queryParameters['candidate_ref'] = requestParameters['candidateRef'];
        }

        if (requestParameters['metadata'] != null) {
            queryParameters['metadata'] = requestParameters['metadata'];
        }

        if (requestParameters['createdAfter'] != null) {
            queryParameters['created_after'] = requestParameters['createdAfter'];
        }

        if (requestParameters['createdBefore'] != null) {
            queryParameters['created_before'] = requestParameters['createdBefore'];
        }

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['expand'] != null) {
            queryParameters['expand'] = requestParameters['expand'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("apiKey", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/interviews`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * `created_after`/`created_before` documented explicitly (step 6 review follow-up, Part A item 8) — without a `#[QueryParameter]` override, Scramble\'s own inference picked up the nearest preceding CODE COMMENT above `$request->query(\'created_after\')` below as this parameter\'s description (an internal implementation note about `validateFilterFormats()`/`Validator::validated()`, meaningless to an API consumer, and `created_before` got no description at all). These two attributes describe the accepted FORMAT and the `400` a caller actually gets on a malformed value, the same contract `App\\Rules\\PublicApi\\Iso8601DateTime` enforces.
     * `data[]` documented as a list of `PublicInterview` objects, and `next_cursor` as the nullable string it genuinely is (step 5 review follow-up, Part B item 2) — `CursorPage::paginate()`\'s own `next_cursor: string|null` PHPDoc did not survive being returned through `response()->json($rawPage)`, so the exported spec previously typed it as a non-nullable `string` and `data[]`\'s items as untyped. `#[IgnoreResponse]`/`#[Response(400, ...)]` (Part B item 6) replace the incorrect auto-inferred `422 {message, errors}` this method\'s own `QueryValidationException` throw produced — see `Problem::PROBLEM_SHAPE`\'s own docblock (step 6 review follow-up, Part A item 6: now shared from `App\\Support\\PublicApi\\Problem` rather than a copy of the constant declared on this class)
     */
    async publicApiInterviewsIndexRaw(requestParameters: PublicApiInterviewsIndexRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PublicApiInterviewsIndex200Response>> {
        const requestOptions = await this.publicApiInterviewsIndexRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PublicApiInterviewsIndex200ResponseFromJSON(jsonValue));
    }

    /**
     * `created_after`/`created_before` documented explicitly (step 6 review follow-up, Part A item 8) — without a `#[QueryParameter]` override, Scramble\'s own inference picked up the nearest preceding CODE COMMENT above `$request->query(\'created_after\')` below as this parameter\'s description (an internal implementation note about `validateFilterFormats()`/`Validator::validated()`, meaningless to an API consumer, and `created_before` got no description at all). These two attributes describe the accepted FORMAT and the `400` a caller actually gets on a malformed value, the same contract `App\\Rules\\PublicApi\\Iso8601DateTime` enforces.
     * `data[]` documented as a list of `PublicInterview` objects, and `next_cursor` as the nullable string it genuinely is (step 5 review follow-up, Part B item 2) — `CursorPage::paginate()`\'s own `next_cursor: string|null` PHPDoc did not survive being returned through `response()->json($rawPage)`, so the exported spec previously typed it as a non-nullable `string` and `data[]`\'s items as untyped. `#[IgnoreResponse]`/`#[Response(400, ...)]` (Part B item 6) replace the incorrect auto-inferred `422 {message, errors}` this method\'s own `QueryValidationException` throw produced — see `Problem::PROBLEM_SHAPE`\'s own docblock (step 6 review follow-up, Part A item 6: now shared from `App\\Support\\PublicApi\\Problem` rather than a copy of the constant declared on this class)
     */
    async publicApiInterviewsIndex(requestParameters: PublicApiInterviewsIndexRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PublicApiInterviewsIndex200Response> {
        const response = await this.publicApiInterviewsIndexRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for publicApiInterviewsScoring without sending the request
     */
    async publicApiInterviewsScoringRequestOpts(requestParameters: PublicApiInterviewsScoringRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['interview'] == null) {
            throw new runtime.RequiredError(
                'interview',
                'Required parameter "interview" was null or undefined when calling publicApiInterviewsScoring().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("apiKey", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/interviews/{interview}/scoring`;
        urlPath = urlPath.replace('{interview}', encodeURIComponent(String(requestParameters['interview'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * `GET /v1/interviews/{id}/scoring` — SPEC.md §3.3, gate: status `completed` only, else `409 scoring_not_ready`
     */
    async publicApiInterviewsScoringRaw(requestParameters: PublicApiInterviewsScoringRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PublicApiInterviewsScoring200Response>> {
        const requestOptions = await this.publicApiInterviewsScoringRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PublicApiInterviewsScoring200ResponseFromJSON(jsonValue));
    }

    /**
     * `GET /v1/interviews/{id}/scoring` — SPEC.md §3.3, gate: status `completed` only, else `409 scoring_not_ready`
     */
    async publicApiInterviewsScoring(requestParameters: PublicApiInterviewsScoringRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PublicApiInterviewsScoring200Response> {
        const response = await this.publicApiInterviewsScoringRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for publicApiInterviewsShow without sending the request
     */
    async publicApiInterviewsShowRequestOpts(requestParameters: PublicApiInterviewsShowRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['interview'] == null) {
            throw new runtime.RequiredError(
                'interview',
                'Required parameter "interview" was null or undefined when calling publicApiInterviewsShow().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['expand'] != null) {
            queryParameters['expand'] = requestParameters['expand'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("apiKey", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/interviews/{interview}`;
        urlPath = urlPath.replace('{interview}', encodeURIComponent(String(requestParameters['interview'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async publicApiInterviewsShowRaw(requestParameters: PublicApiInterviewsShowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PublicInterview>> {
        const requestOptions = await this.publicApiInterviewsShowRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PublicInterviewFromJSON(jsonValue));
    }

    /**
     */
    async publicApiInterviewsShow(requestParameters: PublicApiInterviewsShowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PublicInterview> {
        const response = await this.publicApiInterviewsShowRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for publicApiInterviewsStore without sending the request
     */
    async publicApiInterviewsStoreRequestOpts(requestParameters: PublicApiInterviewsStoreRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createInterviewRequest'] == null) {
            throw new runtime.RequiredError(
                'createInterviewRequest',
                'Required parameter "createInterviewRequest" was null or undefined when calling publicApiInterviewsStore().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("apiKey", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/interviews`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateInterviewRequestToJSON(requestParameters['createInterviewRequest']),
        };
    }

    /**
     * `interview` documented as the `PublicInterview` object it always is (step 5 review follow-up, Part B item 1) — `response()->json([...])`\'s own inferred type only ever saw `InterviewResource::resolve()`\'s loose `array<string, mixed>` return type, so the exported spec previously carried an untyped array here instead of a `$ref`. `#[Response(201, ...)]` (not a bare `@response` PHPDoc tag) — the PHPDoc form replaces Scramble\'s ENTIRE inferred response, collapsing the real `201` this method actually returns down to a default `200`; the attribute form names the status explicitly and overlays onto the response Scramble already inferred at it, leaving the other auto-inferred statuses (`404`, `409`, `422`) untouched. `metadata`\'s accepted shape (Part B item 3) is corrected at its source — `App\\Rules\\PublicApi\\Metadata::docs()` — rather than here, so `CreateInterviewRequest`\'s own named schema carries the fix directly instead of an `allOf` overlay fighting the same property\'s wrong type inside it
     */
    async publicApiInterviewsStoreRaw(requestParameters: PublicApiInterviewsStoreRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PublicApiInterviewsStore201Response>> {
        const requestOptions = await this.publicApiInterviewsStoreRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PublicApiInterviewsStore201ResponseFromJSON(jsonValue));
    }

    /**
     * `interview` documented as the `PublicInterview` object it always is (step 5 review follow-up, Part B item 1) — `response()->json([...])`\'s own inferred type only ever saw `InterviewResource::resolve()`\'s loose `array<string, mixed>` return type, so the exported spec previously carried an untyped array here instead of a `$ref`. `#[Response(201, ...)]` (not a bare `@response` PHPDoc tag) — the PHPDoc form replaces Scramble\'s ENTIRE inferred response, collapsing the real `201` this method actually returns down to a default `200`; the attribute form names the status explicitly and overlays onto the response Scramble already inferred at it, leaving the other auto-inferred statuses (`404`, `409`, `422`) untouched. `metadata`\'s accepted shape (Part B item 3) is corrected at its source — `App\\Rules\\PublicApi\\Metadata::docs()` — rather than here, so `CreateInterviewRequest`\'s own named schema carries the fix directly instead of an `allOf` overlay fighting the same property\'s wrong type inside it
     */
    async publicApiInterviewsStore(requestParameters: PublicApiInterviewsStoreRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PublicApiInterviewsStore201Response> {
        const response = await this.publicApiInterviewsStoreRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for publicApiInterviewsTranscript without sending the request
     */
    async publicApiInterviewsTranscriptRequestOpts(requestParameters: PublicApiInterviewsTranscriptRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['interview'] == null) {
            throw new runtime.RequiredError(
                'interview',
                'Required parameter "interview" was null or undefined when calling publicApiInterviewsTranscript().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("apiKey", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/interviews/{interview}/transcript`;
        urlPath = urlPath.replace('{interview}', encodeURIComponent(String(requestParameters['interview'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * `GET /v1/interviews/{id}/transcript` — SPEC.md §3.3, gate: status `under_evaluation` or `completed`, else `409 transcript_not_ready` (`error` included — G-15)
     */
    async publicApiInterviewsTranscriptRaw(requestParameters: PublicApiInterviewsTranscriptRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PublicApiInterviewsTranscript200Response>> {
        const requestOptions = await this.publicApiInterviewsTranscriptRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PublicApiInterviewsTranscript200ResponseFromJSON(jsonValue));
    }

    /**
     * `GET /v1/interviews/{id}/transcript` — SPEC.md §3.3, gate: status `under_evaluation` or `completed`, else `409 transcript_not_ready` (`error` included — G-15)
     */
    async publicApiInterviewsTranscript(requestParameters: PublicApiInterviewsTranscriptRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PublicApiInterviewsTranscript200Response> {
        const response = await this.publicApiInterviewsTranscriptRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
