/* tslint:disable */
/* eslint-disable */
/**
 * BEAI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.57.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type InlineObject,
    InlineObjectFromJSON,
    InlineObjectToJSON,
} from '../models/InlineObject';
import {
    type PublicApiExportsIndex400Response,
    PublicApiExportsIndex400ResponseFromJSON,
    PublicApiExportsIndex400ResponseToJSON,
} from '../models/PublicApiExportsIndex400Response';
import {
    type PublicApiProjectsIndex200Response,
    PublicApiProjectsIndex200ResponseFromJSON,
    PublicApiProjectsIndex200ResponseToJSON,
} from '../models/PublicApiProjectsIndex200Response';
import {
    type PublicProject,
    PublicProjectFromJSON,
    PublicProjectToJSON,
} from '../models/PublicProject';

export interface PublicApiProjectsIndexRequest {
    /**
     * Opaque pagination cursor from a previous page's next_cursor. Omit for the first page. A present but malformed value answers 400 invalid_cursor.
     */
    cursor?: string;
    /**
     * Page size, 1-100 (default 25). Out of range answers 400 validation_failed.
     */
    limit?: number;
    /**
     * Filter by project status.
     */
    status?: string;
    /**
     * Filter by role code (ICO, FLL, MLL, BUL, SRX).
     */
    roleCode?: string;
    /**
     * Filter by assessment type (standard or potential).
     */
    assessmentType?: string;
}

export interface PublicApiProjectsShowRequest {
    /**
     * 
     */
    project: string;
}

/**
 * 
 */
export class ProjectApi extends runtime.BaseAPI {

    /**
     * Creates request options for publicApiProjectsIndex without sending the request
     */
    async publicApiProjectsIndexRequestOpts(requestParameters: PublicApiProjectsIndexRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['roleCode'] != null) {
            queryParameters['role_code'] = requestParameters['roleCode'];
        }

        if (requestParameters['assessmentType'] != null) {
            queryParameters['assessment_type'] = requestParameters['assessmentType'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("apiKey", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/projects`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * `data[]` documented as a list of `PublicProject` objects and `next_cursor` as nullable (step 5 review follow-up, Part B item 2) — same fix, same reasoning, as `InterviewController::index()`\'s own docblock. `#[IgnoreResponse]`/`#[Response(400, ...)]` (Part B item 6) replace the incorrect auto-inferred `422` this method\'s own `QueryValidationException` throw produced — the shape now shared from `Problem::PROBLEM_SHAPE` (step 6 review follow-up, Part A item 6) rather than a copy of the constant this class used to declare.
     * SPEC.md §3.2 \"Filtering on list endpoints: `status`, ...\". `role_code` and `assessment_type` are Public-API-specific additions this operation\'s own contract entry lists (`openapi.yaml` `listProjects` parameters). An unrecognised value for any of the three answers `400 validation_failed` via `QueryValidationException` (G-28) — a malformed QUERY PARAMETER, never `422`
     */
    async publicApiProjectsIndexRaw(requestParameters: PublicApiProjectsIndexRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PublicApiProjectsIndex200Response>> {
        const requestOptions = await this.publicApiProjectsIndexRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PublicApiProjectsIndex200ResponseFromJSON(jsonValue));
    }

    /**
     * `data[]` documented as a list of `PublicProject` objects and `next_cursor` as nullable (step 5 review follow-up, Part B item 2) — same fix, same reasoning, as `InterviewController::index()`\'s own docblock. `#[IgnoreResponse]`/`#[Response(400, ...)]` (Part B item 6) replace the incorrect auto-inferred `422` this method\'s own `QueryValidationException` throw produced — the shape now shared from `Problem::PROBLEM_SHAPE` (step 6 review follow-up, Part A item 6) rather than a copy of the constant this class used to declare.
     * SPEC.md §3.2 \"Filtering on list endpoints: `status`, ...\". `role_code` and `assessment_type` are Public-API-specific additions this operation\'s own contract entry lists (`openapi.yaml` `listProjects` parameters). An unrecognised value for any of the three answers `400 validation_failed` via `QueryValidationException` (G-28) — a malformed QUERY PARAMETER, never `422`
     */
    async publicApiProjectsIndex(requestParameters: PublicApiProjectsIndexRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PublicApiProjectsIndex200Response> {
        const response = await this.publicApiProjectsIndexRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for publicApiProjectsShow without sending the request
     */
    async publicApiProjectsShowRequestOpts(requestParameters: PublicApiProjectsShowRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['project'] == null) {
            throw new runtime.RequiredError(
                'project',
                'Required parameter "project" was null or undefined when calling publicApiProjectsShow().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("apiKey", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/projects/{project}`;
        urlPath = urlPath.replace('{project}', encodeURIComponent(String(requestParameters['project'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * `$project` is the RAW path segment (`prj_...`), resolved manually rather than through implicit Eloquent route-model binding: the existing admin `Route::apiResource(\'projects\', ProjectController::class)` already binds the SAME `{project}` route parameter name to an integer id, and a second, public-id-based binding registered on the same parameter name would either collide with it or require touching `App\\Models\\Project::resolveRouteBinding()` globally — which the admin surface must never see (it keeps using integer ids). Resolving by hand here keeps the two surfaces fully independent, and `PublicId::decode()` returning `null` on ANY malformed/mismatched- prefix input, funnelled into the exact same \"no row\" 404 branch as a syntactically valid but unknown id, is what guarantees a mismatched prefix answers `404 not_found`, never `400` (SPEC.md §3.2)
     */
    async publicApiProjectsShowRaw(requestParameters: PublicApiProjectsShowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PublicProject>> {
        const requestOptions = await this.publicApiProjectsShowRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PublicProjectFromJSON(jsonValue));
    }

    /**
     * `$project` is the RAW path segment (`prj_...`), resolved manually rather than through implicit Eloquent route-model binding: the existing admin `Route::apiResource(\'projects\', ProjectController::class)` already binds the SAME `{project}` route parameter name to an integer id, and a second, public-id-based binding registered on the same parameter name would either collide with it or require touching `App\\Models\\Project::resolveRouteBinding()` globally — which the admin surface must never see (it keeps using integer ids). Resolving by hand here keeps the two surfaces fully independent, and `PublicId::decode()` returning `null` on ANY malformed/mismatched- prefix input, funnelled into the exact same \"no row\" 404 branch as a syntactically valid but unknown id, is what guarantees a mismatched prefix answers `404 not_found`, never `400` (SPEC.md §3.2)
     */
    async publicApiProjectsShow(requestParameters: PublicApiProjectsShowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PublicProject> {
        const response = await this.publicApiProjectsShowRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
